# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rservice.proto\"\x06\n\x04Null\"J\n\x10Time_Calculation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x13\n\x0btime_period\x18\x03 \x01(\r\"(\n\x0b\x43\x61lc_Result\x12\x19\n\x11\x65xpected_dateline\x18\x01 \x01(\t2\\\n\x0bTestService\x12\x16\n\x06Health\x12\x05.Null\x1a\x05.Null\x12\x35\n\x12\x41\x64\x64TimeCalculation\x12\x11.Time_Calculation\x1a\x0c.Calc_Resultb\x06proto3')
)




_NULL = _descriptor.Descriptor(
  name='Null',
  full_name='Null',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=23,
)


_TIME_CALCULATION = _descriptor.Descriptor(
  name='Time_Calculation',
  full_name='Time_Calculation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Time_Calculation.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='Time_Calculation.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_period', full_name='Time_Calculation.time_period', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=99,
)


_CALC_RESULT = _descriptor.Descriptor(
  name='Calc_Result',
  full_name='Calc_Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='expected_dateline', full_name='Calc_Result.expected_dateline', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['Null'] = _NULL
DESCRIPTOR.message_types_by_name['Time_Calculation'] = _TIME_CALCULATION
DESCRIPTOR.message_types_by_name['Calc_Result'] = _CALC_RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Null = _reflection.GeneratedProtocolMessageType('Null', (_message.Message,), dict(
  DESCRIPTOR = _NULL,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:Null)
  ))
_sym_db.RegisterMessage(Null)

Time_Calculation = _reflection.GeneratedProtocolMessageType('Time_Calculation', (_message.Message,), dict(
  DESCRIPTOR = _TIME_CALCULATION,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:Time_Calculation)
  ))
_sym_db.RegisterMessage(Time_Calculation)

Calc_Result = _reflection.GeneratedProtocolMessageType('Calc_Result', (_message.Message,), dict(
  DESCRIPTOR = _CALC_RESULT,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:Calc_Result)
  ))
_sym_db.RegisterMessage(Calc_Result)



_TESTSERVICE = _descriptor.ServiceDescriptor(
  name='TestService',
  full_name='TestService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=143,
  serialized_end=235,
  methods=[
  _descriptor.MethodDescriptor(
    name='Health',
    full_name='TestService.Health',
    index=0,
    containing_service=None,
    input_type=_NULL,
    output_type=_NULL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddTimeCalculation',
    full_name='TestService.AddTimeCalculation',
    index=1,
    containing_service=None,
    input_type=_TIME_CALCULATION,
    output_type=_CALC_RESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TESTSERVICE)

DESCRIPTOR.services_by_name['TestService'] = _TESTSERVICE

# @@protoc_insertion_point(module_scope)
